# Generated by Django 3.2.10 on 2023-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OysterPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('note_image', models.ImageField(upload_to='notes/')),
            ],
        ),
    ]
